create table if not exists publishers
(
    publisher_id bigserial primary key,
    publisher_title varchar(250) not null
);

create table if not exists genres
(
    genre_id bigserial primary key,
    genre_name varchar(250) not null
);

create table if not exists authors
(
    author_id bigserial primary key,
    author_name varchar(250) not null
);

create table if not exists languages
(
    language_id bigserial primary key,
    language_name varchar(250) not null
);

create table if not exists books
(
    book_id bigserial primary key,
    title varchar(250) not null,
    author_id bigint references authors(author_id),
    publisher_id bigint references publishers(publisher_id),
    genre_id bigint references genres(genre_id),
    isbn_id bigint,
    language_id bigint references languages(language_id)
);

create table if not exists isbn_table
(
    isbn_id bigserial primary key,
    isbn_number varchar(250) not null
--     book_id bigint
);

alter table isbn_table drop constraint if exists book_id;
alter table books drop constraint if exists isbn_id;
alter table if exists books add constraint isbn_id foreign key (isbn_id) references isbn_table(isbn_id);
alter table if exists isbn_table add constraint book_id foreign key (book_id) references books(book_id);

create table if not exists cities
(
    city_id bigserial primary key,
    title varchar(250) not null
);

create table if not exists clients
(
    client_id bigserial primary key,
    client_name varchar(250) not null,
    email varchar(250) not null,
--     phone varchar(250) not null,
    client_address varchar(250) not null,
    city_id bigint references cities(city_id)
);

create table if not exists roles
(
    id int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists users
(
    id int8 generated by default as identity,
    password varchar(255),
    username varchar(255),
    primary key (id)
);

create table if not exists users_roles
(
    users_id int8 not null references users,
    roles_id int8 not null references roles,
    primary key (users_id, roles_id)
);

create table if not exists sales
(
    sale_id bigserial primary key,
    sale_date date,
    book_id bigint references books(book_id),
    price decimal(8,2),
    amount bigint,
    client_id bigint references clients(client_id)
);

create table if not exists suppliers
(
    supplier_id bigserial primary key,
    supplier_name varchar(250) not null
);

create table if not exists supplies
(
    supply_id bigserial primary key,
    supply_date date,
    supplier_id bigint references suppliers(supplier_id)
);

create table if not exists supply_details
(
    supply_detail_id bigserial primary key,
    book_id bigint references books(book_id),
    price decimal(8,2),
    amount bigint,
    supply_id bigint references supplies(supply_id)
);